from dataclasses import asdict
from typing import Callable
import re


#Standardizes the app_name/stack_name to conform to a standard that most AWS services would accept.
#This also implements a maximum allowed app_name length of 40 characters that can be changed if needed.
def sanitize_name(unsanitized_name : str) -> str:

    max_length = 40

    #This removes any symbol that isn't a hyphen or underscore
    #Underscores are retained here, and replaced below, because they are often used in separating words
    removing_most_symbols = re.sub('[^0-9a-zA-Z-_]+', '', unsanitized_name)

    #Replacing underscores with hyphens to retain readability in names 
    underscore_replacement = re.sub('_+', '-',removing_most_symbols)

    #If any hyphens occur two or more times in a row, replaces it with one hyphen. Lowercases the result
    sanitized_app_name = re.sub('-{2,}', '-', underscore_replacement).lower()

    if len(sanitized_app_name) > 0 :
        returned_name = sanitized_app_name[:max_length]
    else:
        returned_name = sanitized_app_name

    return returned_name


def recurse_create_parameter_hash(key_path : list[str], item : str | int | dict, object : dict, param_creation_method : Callable, key_prefix : str = None) -> None:
    """
    Recurse and Create Parameter Hash
    
    This method recuses through the object starting at the key_path. For each key, it creates a secrets manager secret

    Parameters:
    - key_path : str
        The current base path for which to recuse through the object, this is the current path we are at.
    - item : str | int | dict
        The item that we are currently recursing through.
    - object : dict
        The object that we are recusively building. The key_string is simply the key_path list concatenated with "_"
    - param_creation_method: function (key_string, value)
        Function to be called, the return value of which will be added to the return hash
        The function will be called with the key_string and value

    """
    # If we don't have an item, then we return
    if item is None:
        return
    # If we have a string, we have a leaf node so we create the parameter
    # And store the secret for ecs tasks
    if isinstance(item, str) or isinstance(item, int) or isinstance(item, list):
        if key_prefix:
            key_path.insert(0, key_prefix)
        key_string = "_".join(key_path).upper()        

        # We set the object[key_string] to be the return value of the param creation method
        object[key_string] = param_creation_method(key_string, str(item))
        return
    
    # Otherwise we are still in a dictionary config or dict, so we check if we have a dict, if not then we error
    if not isinstance(item, dict):  
        # There's an error with the type since it isn't a dictionary
        # We try typecasting it:
        item = asdict(item)
        
        # print(key_path)
        # print(item)
        # print(type(item))
        # print("ALERT: Unknown Type, cannot proceed")
        # return
    # Otherwise, we continue down the tree but first append the current key
    for key in item:
        new_key_path = key_path[:]
        new_key_path.append(key)
        recurse_create_parameter_hash(new_key_path, item[key], object, param_creation_method, key_prefix)

    return


def generate_parameter_hashes_from_object(input_object : dict, base_keys: list[str], param_creation_method : Callable, separate_hashes : bool = False, key_prefix : str = None) -> dict:
    """
    Generate Parameter and Hashes

    This method generates the parameters and hashes for the various application configurations.
    This creates and returns a dict using the recusive private function "__recurse_create_parameter_and_hash" from the configuration object.

    Parameters:
    - input_object : dict
        The dictionary to find the keys in
    - base_keys : list[str]
        A list of keys to create the parameter hash from
    - separate_hashes : bool
        Wether each base key should have it's own entry in the returned hash

    Returns :
    - dict : the object generated by recursively going through the configuration object with the base_keys.
    """
    temp_hash = {}
    returned_hash = {}
    for base_key in base_keys:
        if base_key in input_object:
            recurse_create_parameter_hash([base_key], input_object[base_key], temp_hash, param_creation_method, key_prefix)
            if separate_hashes:
                returned_hash[base_key] = temp_hash
                temp_hash = {}

    if separate_hashes:
        return returned_hash
    
    return temp_hash