import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthenticatorLayout from "./amplify/AuthenticatorLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const AWSAmplifyLayout = ({children} : Readonly<{
    children: React.ReactNode;
  }>) => {

  console.log("Checking for amplify")
  let amplifyEnabled = process.env.AWS_SERVICES_AMPLIFY_ENABLED ? process.env.AWS_SERVICES_AMPLIFY_ENABLED == 'true' : false
  console.log(amplifyEnabled)

  if (amplifyEnabled) {
    return (
      <AuthenticatorLayout>
        {children}
      </AuthenticatorLayout>
    )
  }

  return children
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AWSAmplifyLayout>
          {children}
        </AWSAmplifyLayout>
      </body>  
    </html>
  );
}
